### ISSUE TITLE
Multiple times in a single line

### ISSUE THREAD

**Issue by ganobrega** [DerekTBrown/inquirer-datepicker-prompt#11]
# Multiple times in a single line
I need to change 4 different times with values: ``08:30 | 12:00 | 13:00 | 18:50``

### Output:
![Captura de Tela 2019-03-12 às 16 43 49](https://user-images.githubusercontent.com/4602864/54230877-1fe85f00-44e6-11e9-9098-d5f16cde7934.png)

### My format option:
```
{
  type: 'datetime',
  name: 'schedule',
  format: [
    'HH', ':', 'MM', ' | ', 
    'HH', ':', 'MM', ' | ', 
    'HH', ':', 'MM', ' | ', 
    'HH', ':', 'MM',
  ]
}

```

**Comment by DerekTBrown** [comment]
This seems like more of a one-off issue than something that is going to serve other people using it.  Can re-open if there is traction for this; but to me it seems like the majority usecase is to just use multiple prompts.
