### ISSUE TITLE
Optional time

### ISSUE THREAD

**Issue by haskellcamargo** [DerekTBrown/inquirer-datepicker-prompt#2]
Is there any flag to omit the time picker? I've being trying to format with `['m', '/', 'd', '/', 'yy']`, but that didn't work.

Thanks in advance and congratulations! The project is awesome!

**Comment by DerekTBrown** [comment]
@haskellcamargo that should work in the latest version(v0.3.3).  

It looks like my call to `_.defaultsDeep()` was also taking the union of the format arrays, forcing the inclusion of the 'TT' parameter.  I have included a working example here:

https://gist.github.com/DerekTBrown/4b6b3357f3c0afbd87021e1c73762a42

Thanks for pointing out the bug!
