### ISSUE TITLE
`filter` field doesn't seem to work

### ISSUE THREAD

**Issue by lucasbento** [DerekTBrown/inquirer-datepicker-prompt#3]
```js
{
  type: 'datetime',
  name: 'time',
  message: '...',
  format: ['HH', ':', 'MM'],
  filter: date => moment(date).format('HH:mm'),
}
```

I'm trying to format the `date` with `moment` but the function doesn't seem to be called, the same happens with `validate`, are those not supported?

**Comment by DerekTBrown** [comment]
Those aren't options supported by this plugin, the full list of supported options is in the readme.

**Comment by DerekTBrown** [comment]
Adding filter, validate, etc support in the latest version.

**Comment by edphn** [comment]
Any progress with those? ;]

**Comment by chief-nerd** [comment]
2017 ... any release?

**Comment by haversnail** [comment]
@lucasbento @edphn @chief-nerd added these options here, FYI: https://github.com/haversnail/inquirer-date-prompt

**Comment by DerekTBrown** [comment]
Implemented this here:

https://github.com/DerekTBrown/inquirer-datepicker-prompt/pull/16
