### ISSUE TITLE
Add a way to format the `default` value

### ISSUE THREAD

**Issue by lucasbento** [DerekTBrown/inquirer-datepicker-prompt#4]
![image](https://user-images.githubusercontent.com/6207220/29860822-96c77e18-8d67-11e7-8837-0bde43d1de66.png)

Add a way to format the `default` value for it not to show as `Wed Aug 30 2017 16:40:00 GMT+0200 (CEST)` but instead `30/08/2017`.

**Comment by DerekTBrown** [comment]
What I did was separate the default from the initial value (as these should be different) in `0.4.0`.

**Comment by lucasbento** [comment]
@DerekTBrown: but will you add the `default` option as it is in the inquirer API?
