### ISSUE TITLE
Remove cursor background color after press enter key

### ISSUE THREAD

**Issue by nuintun** [DerekTBrown/inquirer-datepicker-prompt#5]
![tim 20170923142100](https://user-images.githubusercontent.com/1730277/30770739-aeed8918-a06a-11e7-982b-ae8197864c9b.png)

After press enter key,  i think remove the cursor will be better ~

**Comment by DerekTBrown** [comment]
Good idea! Feel free to submit a PR!

**Comment by nuintun** [comment]
@DerekTBrown 

![tim 20170924104856](https://user-images.githubusercontent.com/1730277/30779005-04049ce2-a116-11e7-883e-6f4c178e9578.png)

![tim 20170924102415](https://user-images.githubusercontent.com/1730277/30778916-ea8c1ea4-a113-11e7-8632-fcb1caf3dc72.png)
